/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import util.ConexionBD;
import java.sql.Connection;

public class Principal {
    public static void main(String[] args) {
        
    }
}
